- group_id: albums
  listset:
    - id: game_decision
      nm: DECISION
      tags:
        - DECISION
    - id: game_rpg
      nm: RPG
      tags:
        - RPG
    - id: game_baroque
      nm: "バロックの城"
      tags:
        - "バロック"
    - id: game_renai
      nm: "夏の恋、いつものキミ"
      tags:
        - "夏恋"
    - id: game_wafu
      nm: "和風短編曲集"
      tags:
        - "和風短編曲集"
    - id: game_aquacocktail
      nm: "アクア カクテル"
      tags:
        - "アクア カクテル"
    - id: game_detective
      nm: "探偵 中園エイジ"
      tags:
        - "探偵"
    - id: game_horror
      nm: "時の館"
      tags:
        - "時の館"
    - id: game_planet
      nm: "エレクトロン"
      tags:
        - "エレクトロン"
    - id: game_lastmonth
      nm: "Last Month"
      tags:
        - "Last Month"
    - id: game_cover
      nm: "ゲーム音楽カバー"
      tags:
        - "ゲーム音楽カバー"
    - id: game_other
      nm: "その他"
      tags:
        - "その他"
- group_id: scenes
  listset:
    - id: scene_cheerful
      nm: "明るい"
      tags:
        - "明るい"
    - id: scene_dark
      nm: "暗い・悲しい"
      tags:
        - "暗い"
    - id: scene_honobono
      nm: "穏やか・安らぎ"
      tags:
        - "穏やか"
    - id: scene_grandeur
      nm: "壮大"
      tags:
        - "壮大"
    - id: scene_mysterious
      nm: "神秘的"
      tags:
        - "神秘的"
    - id: scene_speedy
      nm: "疾走感"
      tags:
        - "疾走感"
    - id: scene_tense
      nm: "緊張感"
      tags:
        - "緊張感"
    - id: scene_night
      nm: "夜"
      tags:
        - "夜"
    - id: scene_cyber
      nm: "サイバー"
      tags:
        - "サイバー"
    - id: scene_piano
      nm: "ピアノ"
      tags:
        - "ピアノ"
    - id: scene_battle
      nm: "バトル"
      tags:
        - "バトル"
    - id: scene_opening
      nm: "オープニング"
      tags:
        - "オープニング"
    - id: scene_ending
      nm: "エンディング"
      tags:
        - "エンディング"
    - id: scene_8bit
      nm: 8bit
      tags:
        - 8bit
